import type { Metadata } from "next";
import { Roboto, Nunito } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthProvider } from "@/contexts/authContext";

const primaryFont = Nunito({ subsets: ["latin"], weight:["400", "700"], variable: "--font-primary" });

const secondaryFont = Roboto({ subsets: ["latin"], weight:["400", "700"], variable: "--font-secondary" });

export const metadata: Metadata = {
  title: "Casa Escalada",
  description: "Generated by Matías López",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html
      lang="es"
      className={`${primaryFont.variable} ${secondaryFont.variable}`}
    >
      <body className={primaryFont.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  </AuthProvider>
  );
}
